---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Define redis_package.
  set_fact:
    redis_package: "{{ __redis_package }}"
  when: redis_package is not defined

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- include: setup-SmartOS.yml
  when: ansible_distribution == 'SmartOS'

#- name: Ensure Redis is configured.
#  template:
#    src: redis.conf.j2
#    dest: "{{ redis_conf_path }}"
#    mode: 0644
#  notify: restart redis

- name: Update the Redis configuration file
  ini_file: >
    dest={{ redis_conf_path }}
    option="{{ item }}"
    section=''
    allow_no_value=yes
  with_items: "{{ redis_config }}"
  when: not((redis_config is undefined) or (redis_config is none) or (redis_config|trim == '') or (item is none))
  notify: restart redis

- name: Ensure Redis is running and enabled on boot.
  service: "name={{ redis_daemon }} state=started enabled=yes"
